### ISSUE TITLE
Cucumberjs errors out with 'element is not attached to the page document'

### ISSUE THREAD

**Issue by YashdalfTheGray** [YashdalfTheGray/cucumber-comparison#1]
I was trying to implement the last step in the step definitions for CucumberJS just as I thought I had it, I ran into this error. Not wanting to look at this more tonight, I decided to log an issue and deal with it later. This is the stack trace when I try to run `pageTitle.getText()` after waiting for the `pageTitle` element to be visible on the page. 

```
Error: Error running instance method
      org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
        (Session info: chrome=48.0.2564.116)
        (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.11.3 x86_64) (WARNING: The server did not provide any stacktrace information)
      Command duration or timeout: 21 milliseconds
      For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
      Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
      System info: host: 'Yashs-MBP-2', ip: '192.168.1.200', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.3', java.version: '1.8.0_74'
      Driver info: org.openqa.selenium.chrome.ChromeDriver
      Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=/var/folders/dh/229j4j150wx04wrjtw9bh6l00000gn/T/.org.chromium.Chromium.RrnUOz}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=48.0.2564.116, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
      Session ID: c0d4eb784322e9385ba583cf5896ee91
      	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
      	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
      	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
      	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
      	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
      	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
      	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:647)
      	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:326)
      	at org.openqa.selenium.remote.RemoteWebElement.getText(RemoteWebElement.java:178)
      	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      	at java.lang.reflect.Method.invoke(Method.java:498)

          at Error (native)
          at WebElement.getText (/Users/yash/git-yash/cucumber-comparison/node_modules/webdriver-sync/src/interfaces/WebElement.js:40:25)
          at World.<anonymous> (/Users/yash/git-yash/cucumber-comparison/test/features/step_definitions/steps.js:35:32)
          at nextTickCallbackWith0Args (node.js:453:9)
          at process._tickCallback (node.js:382:13)
          at Function.Module.runMain (module.js:449:11)
```

Any ideas @kmckee @kwpeters?

**Comment by kmckee** [comment]
Stale elements usually come up if something dynamic happens that replaces an item in the Dom. 

I can't remember the variable name off hand, but we had some element that we found and then assigned to a variable. Then we used it in the wait. Then we used the same variable after the wait to do stuff. 

I bet if you remove the variable and find the element on those two lines it might fix this. Basically, get the element every time rather than storing a reference to it.

**Comment by YashdalfTheGray** [comment]
@kmckee it seems like no matter what I do, I either get a stale reference to that h2 element or any other element that I try to find on the page that's specific to that page ends up getting not found. I blame cucumberjs and selenium and am going back to ruby land. 

Maybe @kwpeters, you can try your hand at getting this last step to work.

**Comment by kmckee** [comment]
Weird, I'm getting it again now, too.  Thought I fixed it the other day.
¯\_(ツ)_/¯

On Fri, Feb 26, 2016 at 10:19 PM, Yash Kulshrestha <notifications@github.com
